### ISSUE TITLE
yaml configuration of validation and test splits for downstream datasets

### ISSUE THREAD

**Issue by franciszchen** [Vision-CAIR/MiniGPT-4#111]
Hi, thanks for sharing this great project! I am transferring the minigpt-4 to a downstream dataset. The training of downstream dataset is fine, but for the validation/test splits I encountered some problems with the dataloaders, where the **vis_processor of the validation/test splits is None**. In the dataloader of validation/test splits, my script can access the samples. I think the **yaml configuration may be some problem**. Here is my configuration for the downstream dataset.

```
datasets:
  downstream_dataset:
    vis_processor:
      train:
        name: "blip2_image_train"
        image_size: 224
    text_processor:
      train:
        name: "blip_caption"
```

I am wondering how to modify it for the validation and test splits, as well as the keywords for them. Thx~
